name: Release
on:
  pull_request:
    types:
      - closed

jobs:
  release:
    runs-on: ubuntu-20.04
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'releases/v')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main

      - uses: actions/setup-node@v2
        with:
          node-version: 12.22.6
          registry-url: "https://npm.pkg.github.com"
          scope: "@hrbrain"

      - run: yarn --prefer-offline
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: yarn shipjs trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
