name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Test with Node.js v10 (LTS), v12 (LTS), and v14 (latest)
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Test
        run: yarn test

      - name: Typecheck
        run: yarn typecheck
